# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/girishpatil935/ML_Internship/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?*

### My lane: Structured Content Archetype Clustering

**ML task type: Unsupervised clustering**

The goal is to group content pages into distinct performance archetypes based on structured metrics such as search volume, impressions, clicks, CTR, average position, content age, and recent performance indicators.

There is no predefined class label that tells us what type of page each page belongs to. Instead, the clustering algorithm will discover groups from the data.

The expected output is a cluster assignment for each content page, followed by a profile of each cluster so that we can understand what makes the pages in that group similar.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*

### Target or proxy

Clustering does not use a supervised target column. There is no existing label in the starter data that defines the correct page archetype.

Instead, the model will generate a new `cluster_id` for each content page. This cluster assignment acts as the output of the ML task rather than a target that we predict from labeled examples.

The cluster will then be interpreted using the original performance metrics to understand what type of pages it represents.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 3. Success metric

*One metric you can defend. What number means 'good'?*

### Success metric

The primary technical metric will be the **Silhouette Score**, which measures how well-separated and internally consistent the clusters are.

However, a high Silhouette Score alone does not mean the clustering is useful. I will also evaluate whether the clusters are interpretable, reasonably sized, stable across reasonable choices of features or random seeds, and meaningfully different in their performance characteristics.

The final goal is therefore not simply to maximize a mathematical score, but to produce clusters that are both technically reasonable and useful for content decision-making.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*

In [1]:
import pandas as pd

# Load the starter dataset
url = "https://raw.githubusercontent.com/flyrank-bih/flyrank-ml-internship-starter/main/data/raw/content_refresh_anonymized.csv"
df = pd.read_csv(url)

print("Dataset shape:", df.shape)

# Show the unit of analysis:
# one row = one content page
columns_to_show = [
    "content_id",
    "search_volume",
    "impressions_90d",
    "avg_position",
    "ctr",
    "content_age_days"
]

# Keep only columns that exist in the dataset
available_columns = [c for c in columns_to_show if c in df.columns]

page_sample = df[available_columns].head(10)

print("\nOne row represents one content page:")
display(page_sample)

Dataset shape: (30000, 44)

One row represents one content page:

,content_id,search_volume,impressions_90d,avg_position,ctr,content_age_days
0,content_304f48230142,10.0,3803,10.6,0.76,187
1,content_a1fb4e703a9e,90.0,15320,20.3,0.05,445
2,content_9aa793d4d895,0.0,12581,36.5,0.09,141
3,content_331d6c4de07b,10.0,11751,6.2,0.49,463
4,content_d99b7a2d90ca,0.0,19140,44.0,0.13,263
5,content_d4084a4bc775,720.0,3970,8.5,0.03,147
6,content_9a34b442b552,0.0,20,7.0,0.00,90
7,content_a63219c6e95a,590.0,1724,21.2,0.06,445
8,content_5e6c160719bc,0.0,32574,46.0,0.09,90
9,content_c27558df2b0c,0.0,1240,4.9,0.16,257

## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*

### Unit of analysis

The unit of analysis is one content page. Each row represents one content item, identified by `content_id`, with its associated search and performance measurements.

The eventual clustering output will add a `cluster_id` to each page:

`content_id → performance features → cluster_id`

This allows us to group and profile pages at the content-item level.

In [2]:
# Sketch the future clustering output.
# cluster_id does not exist yet; the clustering model will create it.

cluster_output = page_sample.copy()

cluster_output["cluster_id"] = None

print("Example structure of the future clustering output:")
display(cluster_output)

Example structure of the future clustering output:

,content_id,search_volume,impressions_90d,avg_position,ctr,content_age_days,cluster_id
0,content_304f48230142,10.0,3803,10.6,0.76,187,None
1,content_a1fb4e703a9e,90.0,15320,20.3,0.05,445,None
2,content_9aa793d4d895,0.0,12581,36.5,0.09,141,None
3,content_331d6c4de07b,10.0,11751,6.2,0.49,463,None
4,content_d99b7a2d90ca,0.0,19140,44.0,0.13,263,None
5,content_d4084a4bc775,720.0,3970,8.5,0.03,147,None
6,content_9a34b442b552,0.0,20,7.0,0.00,90,None
7,content_a63219c6e95a,590.0,1724,21.2,0.06,445,None
8,content_5e6c160719bc,0.0,32574,46.0,0.09,90,None
9,content_c27558df2b0c,0.0,1240,4.9,0.16,257,None

### Why ML beats a fixed rule

A fixed rule could manually define categories such as "high impressions" or "low CTR", but such thresholds may oversimplify the different ways pages can perform.

Clustering can consider several metrics together and discover combinations of characteristics that may not be obvious from individual thresholds. For example, two pages may have similar impressions but very different CTR, position, content age, or search demand.

The advantage of ML here is therefore not that it automatically decides what to do with a page. Its advantage is that it can help discover groups of pages with similar multi-dimensional performance patterns that can then be investigated and interpreted by a content team.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.

### Self-check

- [x] Task type identified: unsupervised clustering.
- [x] No supervised target is assumed because page archetypes are not pre-labeled.
- [x] The future output is a `cluster_id` assigned to each content page.
- [x] Primary technical metric identified: Silhouette Score.
- [x] Cluster quality will also be judged by interpretability, stability, and usefulness.
- [x] Unit of analysis identified: one content page per row.
- [x] A real dataframe from the starter dataset is shown.
- [x] The clustering output structure has been sketched.
- [x] The reason for using ML instead of fixed thresholds is explained.
- [x] The output is connected to future content decisions.